language: node_js
node_js:
   — “8”
script:
  — echo “Deploy!!”
install:
  — npm install - g firebase - tools
after_success:
   — firebase deploy — project projectId — token $FIREBASE_TOKEN.
after_success:
  —npm build --prod
  —firebase deploy  — project matthieu-f1348 — token $FIREBASE_TOKEN