language: node_js
node_js:  
  8
script:
  npm install
  npm run build --prod
install:
  npm install -g firebase-tools
after_success:
  firebase deploy  - project matthieu-f1348 - token $FIREBASE_TOKEN