language: node_js
node_js:  
  8
install:
  npm install -g firebase-tools
  npm install
script:
  npm run build --prod
before_deploy:
  firebase use--token $FIREBASE_TOKEN matthieu - f1348
deploy:
  firebase deploy --non-interactive --token $FIREBASE_DEPLOY_KEY